# Generated by Django 5.0.7 on 2024-07-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_country_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishtype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
