# Generated by Django 5.0.7 on 2024-07-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dishtype_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
